// config/weapons.js · 武器数据（10 种）
export const WEAPONS = {
  flail:     { name:'连枷', kind:'orbit',     color:'#c0c0d0', desc:'两颗铁球绕身旋转，碾碎近身敌人。',
               base:{ dmg:14, cd:0, count:2, size:16, radius:70, speed:2.6, knock:120 },
               up:['+1 铁球','+旋转半径','+伤害','+旋转速度','+球体积'] },
  fireball:  { name:'火球', kind:'nearest',   color:'#ff7b3c', desc:'朝最近敌人喷火球，穿透并点燃。',
               base:{ dmg:22, cd:1.1, count:1, size:11, speed:420, pierce:2, knock:40 },
               up:['+1 发','-冷却','+伤害','+穿透','+弹速'] },
  shuriken:  { name:'飞镖', kind:'spread',    color:'#d8d8e8', desc:'扇形撒出旋转飞镖，覆盖面广。',
               base:{ dmg:9, cd:0.85, count:3, size:9, speed:460, pierce:1, spread:0.5, knock:20 },
               up:['+1 发','-冷却','+伤害','+穿透','+扩散'] },
  boomerang: { name:'回旋镖', kind:'boomerang', color:'#ffcf6b', desc:'飞出去再飞回来，来回两段伤害。',
               base:{ dmg:18, cd:1.5, count:1, size:13, speed:380, pierce:99, range:260, knock:50 },
               up:['+1 发','-冷却','+伤害','+飞行距离','+体积'] },
  tesla:     { name:'特斯拉线圈', kind:'chain', color:'#7ec8ff', desc:'闪电在敌群间连锁跳跃。',
               base:{ dmg:16, cd:1.4, count:1, chains:3, range:180, size:6, knock:10 },
               up:['+1 目标','-冷却','+伤害','+跳跃数','+射程'] },
  blackhole: { name:'黑洞', kind:'area',       color:'#a06bff', desc:'定期在附近生成黑洞，吸拢并灼烧。',
               base:{ dmg:8, cd:4.5, count:1, size:70, dur:2.5, pull:180, knock:0 },
               up:['+1 个','-冷却','+伤害','+范围','+持续'] },
  minefield: { name:'地雷阵', kind:'mine',     color:'#ff5a5a', desc:'脚下埋雷，敌人踩到就炸。',
               base:{ dmg:34, cd:1.8, count:1, size:26, speed:0, knock:80, dur:8 },
               up:['+1 雷','-冷却','+伤害','+爆炸范围','+存在时间'] },
  leech:     { name:'水蛭镖', kind:'nearest',  color:'#3ad06b', desc:'命中回血的绿镖，续航神器。',
               base:{ dmg:12, cd:1.3, count:1, size:10, speed:400, pierce:1, life:0.12, knock:20 },
               up:['+1 发','-冷却','+伤害','+吸血','+穿透'] },
  iceorb:    { name:'冰球', kind:'spread',     color:'#8fe8ff', desc:'冰球减速命中的敌人，控场。',
               base:{ dmg:10, cd:1.6, count:2, size:12, speed:300, pierce:2, slow:0.45, slowDur:1.6, spread:0.7, knock:30 },
               up:['+1 发','-冷却','+伤害','+减速强度','+穿透'] },
  crossbow:  { name:'连弩', kind:'nearest',    color:'#e8d8a0', desc:'高频锁定最近敌人的箭矢。',
               base:{ dmg:8, cd:0.5, count:1, size:8, speed:560, pierce:1, crit:0.2, knock:15 },
               up:['+1 发','-冷却','+伤害','+暴击率','+穿透'] }
};
export const WEAPON_IDS = Object.keys(WEAPONS);
